# Generated by Django 6.0.2 on 2026-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalJumat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('khatib', models.CharField(max_length=200, verbose_name='Khatib')),
                ('imam', models.CharField(max_length=200, verbose_name='Imam')),
                ('tema', models.CharField(blank=True, max_length=300, verbose_name='Tema Khutbah')),
            ],
            options={
                'verbose_name': 'Jadwal Jumat',
                'verbose_name_plural': 'Jadwal Jumat',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='JadwalSholat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True, verbose_name='Tanggal')),
                ('subuh', models.TimeField(verbose_name='Subuh')),
                ('terbit', models.TimeField(verbose_name='Terbit')),
                ('dzuhur', models.TimeField(verbose_name='Dzuhur')),
                ('ashar', models.TimeField(verbose_name='Ashar')),
                ('maghrib', models.TimeField(verbose_name='Maghrib')),
                ('isya', models.TimeField(verbose_name='Isya')),
            ],
            options={
                'verbose_name': 'Jadwal Sholat',
                'verbose_name_plural': 'Jadwal Sholat',
                'ordering': ['-tanggal'],
            },
        ),
    ]
