# Generated by Django 6.0.2 on 2026-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sholat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SholatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=-6.2088, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=106.8456, verbose_name='Longitude')),
                ('timezone', models.CharField(default='Asia/Jakarta', max_length=50, verbose_name='Zona Waktu')),
                ('koreksi_subuh', models.IntegerField(default=2, verbose_name='Koreksi Subuh')),
                ('koreksi_dzuhur', models.IntegerField(default=2, verbose_name='Koreksi Dzuhur')),
                ('koreksi_ashar', models.IntegerField(default=2, verbose_name='Koreksi Ashar')),
                ('koreksi_maghrib', models.IntegerField(default=2, verbose_name='Koreksi Maghrib')),
                ('koreksi_isya', models.IntegerField(default=2, verbose_name='Koreksi Isya')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Sholat',
                'verbose_name_plural': 'Pengaturan Sholat',
            },
        ),
        migrations.DeleteModel(
            name='JadwalSholat',
        ),
    ]
