# Generated by Django 6.0.2 on 2026-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300, verbose_name='Judul Kegiatan')),
                ('deskripsi', models.TextField(verbose_name='Deskripsi')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('waktu_mulai', models.TimeField(verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.TimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
                ('tempat', models.CharField(max_length=300, verbose_name='Tempat')),
                ('narasumber', models.CharField(blank=True, max_length=300, verbose_name='Narasumber / Pemateri')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='kegiatan/', verbose_name='Gambar')),
                ('status', models.CharField(choices=[('upcoming', 'Akan Datang'), ('ongoing', 'Berlangsung'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='upcoming', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Kegiatan',
                'verbose_name_plural': 'Kegiatan',
                'ordering': ['-tanggal'],
            },
        ),
    ]
