# Generated by Django 6.0.2 on 2026-02-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donatur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Donatur')),
                ('tipe', models.CharField(choices=[('tetap', 'Donatur Tetap'), ('tidak_tetap', 'Donatur Tidak Tetap')], default='tidak_tetap', max_length=20, verbose_name='Tipe Donatur')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=20, verbose_name='Status')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Telepon/WA')),
                ('komitmen_rutin', models.DecimalField(decimal_places=0, default=0, help_text='Jumlah donasi rutin (jika donatur tetap)', max_digits=12, verbose_name='Komitmen Rutin (Rp)')),
                ('tipe_rutin', models.CharField(blank=True, choices=[('bulanan', 'Bulanan'), ('mingguan', 'Mingguan'), ('tahunan', 'Tahunan')], default='bulanan', max_length=20, null=True, verbose_name='Periode Rutin')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donatur',
                'verbose_name_plural': 'Data Donatur',
                'ordering': ['nama'],
            },
        ),
    ]
