# Generated by Django 6.0.2 on 2026-02-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Fasilitas')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(default='bi-building', max_length=100, verbose_name='Icon (Bootstrap Icon class)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Fasilitas',
                'verbose_name_plural': 'Fasilitas',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama')),
                ('jabatan', models.CharField(choices=[('ketua', 'Ketua'), ('wakil_ketua', 'Wakil Ketua'), ('sekretaris', 'Sekretaris'), ('bendahara', 'Bendahara'), ('anggota', 'Anggota')], max_length=50, verbose_name='Jabatan')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengurus/', verbose_name='Foto')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Pengurus',
                'verbose_name_plural': 'Pengurus',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='ProfilMasjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Masjid')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Tagline')),
                ('sejarah', models.TextField(verbose_name='Sejarah')),
                ('visi', models.TextField(verbose_name='Visi')),
                ('misi', models.TextField(verbose_name='Misi')),
                ('alamat', models.TextField(verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=20, verbose_name='Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil/', verbose_name='Foto Masjid')),
                ('maps_embed', models.TextField(blank=True, verbose_name='Google Maps Embed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
            ],
            options={
                'verbose_name': 'Profil Masjid',
                'verbose_name_plural': 'Profil Masjid',
            },
        ),
    ]
