# Generated by Django 6.0.2 on 2026-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmasjid',
            name='koreksi_ashar',
            field=models.IntegerField(default=2, verbose_name='Koreksi Ashar'),
        ),
        migrations.AddField(
            model_name='profilmasjid',
            name='koreksi_dzuhur',
            field=models.IntegerField(default=2, verbose_name='Koreksi Dzuhur'),
        ),
        migrations.AddField(
            model_name='profilmasjid',
            name='koreksi_isya',
            field=models.IntegerField(default=2, verbose_name='Koreksi Isya'),
        ),
        migrations.AddField(
            model_name='profilmasjid',
            name='koreksi_maghrib',
            field=models.IntegerField(default=2, verbose_name='Koreksi Maghrib'),
        ),
        migrations.AddField(
            model_name='profilmasjid',
            name='koreksi_subuh',
            field=models.IntegerField(default=2, verbose_name='Koreksi Subuh'),
        ),
        migrations.AddField(
            model_name='profilmasjid',
            name='latitude',
            field=models.FloatField(default=-6.2088, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='profilmasjid',
            name='longitude',
            field=models.FloatField(default=106.8456, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='profilmasjid',
            name='timezone',
            field=models.CharField(default='Asia/Jakarta', max_length=50, verbose_name='Zona Waktu'),
        ),
    ]
