# Generated by Django 6.0.2 on 2026-02-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profilmasjid_koreksi_ashar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilmasjid',
            name='koreksi_ashar',
        ),
        migrations.RemoveField(
            model_name='profilmasjid',
            name='koreksi_dzuhur',
        ),
        migrations.RemoveField(
            model_name='profilmasjid',
            name='koreksi_isya',
        ),
        migrations.RemoveField(
            model_name='profilmasjid',
            name='koreksi_maghrib',
        ),
        migrations.RemoveField(
            model_name='profilmasjid',
            name='koreksi_subuh',
        ),
        migrations.RemoveField(
            model_name='profilmasjid',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profilmasjid',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profilmasjid',
            name='timezone',
        ),
    ]
