# Generated by Django 6.0.2 on 2026-02-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_remove_profilmasjid_koreksi_ashar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodePengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: Periode 2024-2029', max_length=100, verbose_name='Nama Periode')),
                ('tahun_mulai', models.IntegerField(verbose_name='Tahun Mulai')),
                ('tahun_selesai', models.IntegerField(verbose_name='Tahun Selesai')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Periode Pengurus',
                'verbose_name_plural': 'Periode Pengurus',
                'ordering': ['-tahun_mulai'],
            },
        ),
        migrations.AddField(
            model_name='pengurus',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengurus_list', to='profil.periodepengurus', verbose_name='Periode'),
        ),
    ]
