# Generated by Django 6.0.2 on 2026-02-19 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('default', 'Default (Hijau)'), ('blue', 'Biru'), ('dark', 'Gelap'), ('maroon', 'Merah Marun'), ('teal', 'Teal'), ('purple', 'Ungu')], default='default', help_text='Tema warna utama website.', max_length=20, verbose_name='Tema Website')),
                ('warna_primary', models.CharField(default='#1a6b3c', help_text='Kode warna HEX untuk warna utama. Contoh: #1a6b3c', max_length=7, verbose_name='Warna Primary')),
                ('warna_accent', models.CharField(default='#f0a500', help_text='Kode warna HEX untuk warna aksen/tombol CTA.', max_length=7, verbose_name='Warna Aksen')),
                ('hero_style', models.CharField(choices=[('gradient', 'Gradient Overlay'), ('solid', 'Warna Solid'), ('image', 'Gambar Saja (tanpa overlay)'), ('video', 'Video Background')], default='gradient', max_length=20, verbose_name='Gaya Hero Section')),
                ('hero_overlay_color', models.CharField(default='#1a6b3c', help_text='Warna dasar untuk overlay hero (gradien).', max_length=7, verbose_name='Warna Overlay Hero')),
                ('hero_overlay_opacity', models.FloatField(default=0.85, help_text='Tingkat kegelapan overlay (0 = transparan, 1 = gelap penuh).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Opasitas Overlay Hero')),
                ('hero_gambar', models.ImageField(blank=True, help_text='Gambar latar belakang hero section. Jika kosong, menggunakan foto masjid.', null=True, upload_to='hero/', verbose_name='Gambar Hero')),
                ('hero_video_url', models.URLField(blank=True, help_text='URL video untuk latar belakang hero (MP4).', verbose_name='URL Video Hero')),
                ('hero_judul', models.CharField(blank=True, help_text='Judul besar di hero section. Kosongkan untuk menggunakan nama masjid.', max_length=200, verbose_name='Judul Hero')),
                ('hero_subjudul', models.CharField(blank=True, help_text='Sub-judul/tagline di hero section. Kosongkan untuk menggunakan tagline masjid.', max_length=300, verbose_name='Sub-Judul Hero')),
                ('homepage_layout', models.CharField(choices=[('default', 'Default (Hero + Jadwal + Kegiatan + Berita)'), ('compact', 'Kompak (Hero kecil + Konten grid)'), ('fullscreen', 'Fullscreen Hero + Scroll Sections'), ('dashboard', 'Dashboard (Tanpa Hero, langsung info)')], default='default', help_text='Pilih tata letak halaman utama.', max_length=20, verbose_name='Layout Homepage')),
                ('tampilkan_logo', models.BooleanField(default=True, verbose_name='Tampilkan Logo di Navbar')),
                ('logo', models.ImageField(blank=True, help_text='Logo untuk navbar. Ukuran disarankan: 40×40 px.', null=True, upload_to='logo/', verbose_name='Logo Website')),
                ('favicon', models.ImageField(blank=True, help_text='Ikon kecil untuk tab browser. Ukuran: 32×32 px.', null=True, upload_to='favicon/', verbose_name='Favicon')),
                ('footer_text', models.CharField(blank=True, help_text='Teks hak cipta di footer. Kosongkan untuk default.', max_length=500, verbose_name='Teks Footer')),
                ('footer_show_social', models.BooleanField(default=True, verbose_name='Tampilkan Sosial Media di Footer')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('tiktok_url', models.URLField(blank=True, verbose_name='TikTok')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('tampilkan_jadwal_sholat', models.BooleanField(default=True, verbose_name='Tampilkan Jadwal Sholat di Beranda')),
                ('tampilkan_kegiatan', models.BooleanField(default=True, verbose_name='Tampilkan Kegiatan di Beranda')),
                ('tampilkan_berita', models.BooleanField(default=True, verbose_name='Tampilkan Berita di Beranda')),
                ('tampilkan_keuangan', models.BooleanField(default=True, verbose_name='Tampilkan Link Keuangan di Menu')),
                ('tampilkan_donasi', models.BooleanField(default=False, verbose_name='Tampilkan Tombol Donasi')),
                ('donasi_teks', models.CharField(blank=True, default='Salurkan donasi terbaik Anda untuk masjid.', max_length=300, verbose_name='Teks Ajakan Donasi')),
                ('rekening_info', models.TextField(blank=True, help_text='Informasi rekening bank untuk donasi (bisa pakai format HTML).', verbose_name='Informasi Rekening')),
                ('qris_image', models.ImageField(blank=True, help_text='Gambar QRIS untuk pembayaran donasi.', null=True, upload_to='donasi/', verbose_name='QRIS/QR Code Donasi')),
                ('meta_description', models.CharField(blank=True, help_text='Deskripsi singkat website untuk SEO.', max_length=300, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Kata kunci SEO, pisahkan dengan koma.', max_length=500, verbose_name='Meta Keywords')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Contoh: G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Tampilkan halaman maintenance ke publik.', verbose_name='Mode Maintenance')),
                ('maintenance_message', models.TextField(blank=True, default='Website sedang dalam perbaikan. Silakan kembali beberapa saat lagi.', verbose_name='Pesan Maintenance')),
                ('custom_css', models.TextField(blank=True, help_text='CSS tambahan yang akan di-inject ke semua halaman.', verbose_name='Custom CSS')),
                ('custom_js', models.TextField(blank=True, help_text='JavaScript tambahan (tanpa tag script).', verbose_name='Custom JavaScript')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diubah')),
            ],
            options={
                'verbose_name': 'Pengaturan Website',
                'verbose_name_plural': 'Pengaturan Website',
            },
        ),
    ]
