# Generated by Django 6.0.2 on 2026-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='Utama', max_length=100, verbose_name='Nama Setting')),
                ('tema', models.CharField(choices=[('default', 'Default (Hijau)'), ('dark', 'Gelap'), ('blue', 'Biru')], default='default', max_length=50, verbose_name='Tema Tampilan')),
                ('durasi_slide', models.PositiveIntegerField(default=10, verbose_name='Durasi Slide (detik)')),
                ('running_text', models.TextField(blank=True, help_text='Teks berjalan di bawah layar', verbose_name='Running Text')),
                ('video_url', models.URLField(blank=True, help_text='Opsional: Link video YouTube atau file video', null=True, verbose_name='URL Video Background')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Display',
                'verbose_name_plural': 'Pengaturan Display',
            },
        ),
    ]
