# Generated by Django 6.0.2 on 2026-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplaySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Slide')),
                ('tipe', models.CharField(choices=[('sholat', 'Jadwal Sholat'), ('kas', 'Informasi Kas'), ('berita', 'Berita & Pengumuman'), ('kegiatan', 'Kegiatan Mendatang'), ('teks', 'Teks Kustom'), ('gambar', 'Gambar')], default='teks', max_length=50, verbose_name='Tipe Konten')),
                ('konten_teks', models.TextField(blank=True, help_text='Untuk tipe Teks Kustom', verbose_name='Konten Teks')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='display/slides/', verbose_name='Gambar Slide')),
                ('durasi', models.PositiveIntegerField(default=15, help_text='Lama slide ditampilkan', verbose_name='Durasi (detik)')),
                ('urutan', models.PositiveIntegerField(default=0, verbose_name='Urutan Tampil')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide Display',
                'verbose_name_plural': 'Slide Display',
                'ordering': ['urutan', 'updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='displaysettings',
            name='durasi_slide',
        ),
    ]
