# Generated by Django 6.0.2 on 2026-02-19 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_displayslide_remove_displaysettings_durasi_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaysettings',
            name='custom_notification',
            field=models.FileField(blank=True, help_text='Opsional: Upload file audio sendiri', null=True, upload_to='display/audio/', verbose_name='Upload Suara Custom'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Jika dicentang, display ini akan muncul di URL /display/ tanpa ID', verbose_name='Default Display'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='layout',
            field=models.CharField(choices=[('classic', 'Classic (Jadwal Kiri, Slide Kanan)'), ('modern', 'Modern (Jadwal Bawah)'), ('sidebar_right', 'Sidebar Kanan'), ('full_slider', 'Full Slider (Jadwal Overlay)'), ('masjid_info', 'Fokus Info Masjid'), ('simple', 'Simple Minimalis'), ('big_clock', 'Jam Besar')], default='classic', max_length=50, verbose_name='Layout Tampilan'),
        ),
        migrations.AddField(
            model_name='displaysettings',
            name='sholat_notification',
            field=models.CharField(blank=True, choices=[('notification-1.mp3', 'Notifikasi 1 (Soft)'), ('notification-2.mp3', 'Notifikasi 2 (Glass)'), ('notification-3.mp3', 'Notifikasi 3 (Bell)'), ('notification-4.mp3', 'Notifikasi 4 (Chime)'), ('', 'Tidak Ada Suara')], default='notification-1.mp3', max_length=100, verbose_name='Suara Masuk Sholat'),
        ),
        migrations.AddField(
            model_name='displayslide',
            name='display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='display.displaysettings', verbose_name='Tampilan'),
        ),
        migrations.AlterField(
            model_name='displaysettings',
            name='tema',
            field=models.CharField(choices=[('default', 'Default (Hijau Masjid)'), ('blue', 'Biru Laut'), ('dark', 'Dark Mode (Monokrom)'), ('gold', 'Emas Elegan'), ('purple', 'Ungu Modern'), ('nature', 'Nuansa Alam (Coklat)')], default='default', max_length=50, verbose_name='Tema Tampilan'),
        ),
    ]
