# Generated by Django 6.0.2 on 2026-02-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama Kategori')),
                ('jenis', models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], max_length=20, verbose_name='Jenis')),
            ],
            options={
                'verbose_name': 'Kategori Keuangan',
                'verbose_name_plural': 'Kategori Keuangan',
                'ordering': ['jenis', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='TransaksiKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('keterangan', models.CharField(max_length=500, verbose_name='Keterangan')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Jumlah (Rp)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keuangan.kategorikeuangan', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Transaksi Keuangan',
                'verbose_name_plural': 'Transaksi Keuangan',
                'ordering': ['-tanggal', '-created_at'],
            },
        ),
    ]
