# Generated by Django 6.0.2 on 2026-02-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBerita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kategori Berita',
                'verbose_name_plural': 'Kategori Berita',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300, verbose_name='Judul')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug')),
                ('isi', models.TextField(verbose_name='Isi')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/', verbose_name='Gambar')),
                ('is_published', models.BooleanField(default=False, verbose_name='Dipublikasikan')),
                ('is_pengumuman', models.BooleanField(default=False, verbose_name='Pengumuman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='berita.kategoriberita', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Berita',
                'ordering': ['-created_at'],
            },
        ),
    ]
